name: UpdateVideos

on:
  workflow_dispatch:
  schedule:
  - cron: "45 * * * *"
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o ${{ github.workspace }}/update 
    - name: Update Profile
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/update
        .\updateStar ${{ secrets.TOKEN }} ${{ secrets.API_URL }}  
    
    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: YOUTUBE
        feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCnQzZNPePG3EZMj7Qg3D0Sw"
        committer_email: "julio.arruda@outlook.com"
        
        
        
      
