name: UpdateVideos

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o ${{ github.workspace }}/update 
    - name: Update Profile
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/update
        .\updateStar.exe ${{ secrets.TOKEN }}  
      
